export default {
    adult: false,
    gender: 2,
    id: 1136406,
    known_for: [
        {
            adult: false,
            backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
            genre_ids: [28, 12, 878, 18],
            id: 315635,
            media_type: "movie",
            original_language: "en",
            original_title: "Spider-Man: Homecoming",
            overview: "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
            poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
            release_date: "2017-07-05",
            title: "Spider-Man: Homecoming",
            video: false,
            vote_average: 7.4,
            vote_count: 19327
        },
        {
            adult: false,
            backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
            genre_ids: [28, 12, 878, 18],
            id: 315635,
            media_type: "movie",
            original_language: "en",
            original_title: "Spider-Man: Homecoming",
            overview: "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
            poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
            release_date: "2017-07-05",
            title: "Spider-Man: Homecoming",
            video: false,
            vote_average: 7.4,
            vote_count: 19327
        },
        {
            adult: false,
            backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
            genre_ids: [28, 12, 878, 18],
            id: 315635,
            media_type: "movie",
            original_language: "en",
            original_title: "Spider-Man: Homecoming",
            overview: "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
            poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
            release_date: "2017-07-05",
            title: "Spider-Man: Homecoming",
            video: false,
            vote_average: 7.4,
            vote_count: 19327
        }
    ],
    known_for_department: "Acting",
    name: "Tom Holland",
    popularity: 140.268,
    profile_path: "/bBRlrpJm9XkNSg0YT5LCaxqoFMX.jpg",
    biography: "Thomas \"Tom\" Stanley Holland is an English actor and dancer.\n\nHe is best known for playing Peter Parker / Spider-Man in the Marvel Cinematic Universe and has appeared as the character in six films: Captain America: Civil War (2016), Spider-Man: Homecoming (2017), Avengers: Infinity War (2018), Avengers: Endgame (2019), Spider-Man: Far From Home (2019), and Spider-Man: No Way Home (2021).\n\nHe is also known for playing the title role in Billy Elliot the Musical at the Victoria Palace Theatre, London, as well as for starring in the 2012 film The Impossible.",
    birthday: "1996-06-01",
    deathday: null,
    place_of_birth: "Surrey, England, UK"
}